<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GACore-windows" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FleetClients.csproj" />
  </ItemGroup>

</Project>
